version: '3.8'

services:
  app:
    build: .
    container_name: enrichment-service-app
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URL=amqp://user-service-rabbitmq:5672
      - PORT=3000
      - NODE_ENV=development
    depends_on:
      - rabbitmq
    networks:
      - user-service-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: enrichment-service-rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - user-service-network

volumes:
  mongodb_data:

networks:
  user-service-network:
    external: true
