version: '3.8'

services:
  app:
    build: .
    container_name: enrichment-service-app
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - RABBITMQ_URL=amqp://user-service-rabbitmq:5672
      - PORT=3000
      - NODE_ENV=development
    networks:
      - user-service-network

networks:
  user-service-network:
    external: true
    name: user-service_user-service-network
